### ISSUE TITLE
Problems with package in 2022.2.9

### ISSUE THREAD

**Issue by redwyre** [Eastrall/Rosalina#23]
# :beetle: Bug Report

**Unity version:** 2022.2.9
**Rosalina version:** 2.0.0

## Description

The package isn't working in Unity 2022.2.9 which seems to be related to including netstandard 2.0 files, while Unity is now using netstandard 2.1.

## Steps to Reproduce

1. Add package via git url to Unity 2022.2.9
2.
3.
4.

## Current Behavior

```
Library\PackageCache\com.unity.render-pipelines.core@14.0.6\Editor\Lighting\ProbeVolume\ProbeGIBaking.cs(1356,30): error CS0433: The type 'ReadOnlySpan<T>' exists in both 'Rosalina.RoslynLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Library\PackageCache\com.unity.render-pipelines.high-definition@14.0.6\Runtime\Lighting\DiffusionProfileList.cs(26,31): error CS0433: The type 'ArrayPool<T>' exists in both 'Rosalina.RoslynLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```

## Expected Behavior

There would be no errors

## Possible Solution

I fiddled around with deleting `Rosalina.RoslynLibrary.dll` and trying to add individual dlls from nuget but didn't get it to work.

**Comment by Randolphjand** [comment]
I added the package to the latest 2023 beta and had no issues.  I also opened a project it was in that I updated to the latest 2022 and it worked.  Maybe you have something else in the project that is causing problems.

**Comment by redwyre** [comment]
It looks like at least HDRP triggers it because it uses types that are duplicated in the library.

It looks like 2021.2 is you minimum supported version, which uses .net standard 2.0 - however 2021.3 and onwards are .net standard 2.1 which makes this issue annoying.

While looking into this I discovered that you can use "Define constraints" to control which DLLs are loaded, so having a second DLL for .net standard 2.1 and use `NET_STANDARD_2_0` and `NET_STANDARD_2_1` defines to toggle which dlls are used.

Alternatively maybe UnityNuGet would be an option for the dependencies: https://github.com/xoofx/UnityNuGet

**Comment by redwyre** [comment]
I'm going to have a crack at this now, is dropping support for 2021.2 a viable option for the next version (it's recommended to be on 2021.3 LTS anyway)?

**Comment by Eastrall** [comment]
Sorry to come back to you so late about this issue.
I believe dropping the support for version 2021.2 can be an option and target 2021.3 LTS instead.

The `Rosalina.RoslynLibrary` is a set of dll merged together that contains the Roslyn code generator dlls, without it, the source code generator wouldn't work. Maybe there is a workaround within package configuration to avoid loading it with HDRP.

Another approach, that i'm sure would work, would be to rewrite the code generators using `string`s instead of using Roslyn syntax, thus we could remove the dependency to Roslyn which may solve your issue.

**Comment by redwyre** [comment]
I've found this package which contains all the required DLLs: https://github.com/merryyellow/code-analysis-3-11.git
I think the issue is the merged DLL merged some dependencies that already exist. Another option is just to rebuild the merged DLL.

For my testing I've nuked the merged DLL and added the above package directly. If you're ok with that package I can add it as a reference, however I like the flexibility of being able to choose how I want to get the DLLs :)

see https://github.com/Eastrall/Rosalina/compare/main...redwyre:Rosalina:main

**Comment by Eastrall** [comment]
Well, instead of merging the dll into a single one, maybe we could just do like the `code-analysis-3-11` package and put all the dll and set the : `overrideReferences` to `true` and add the `precompiledReferences` just like you did in your commit. Doing this, we do not depend on any other third party unity package, just Microsoft's Code analysis dll.

Let me know what you think of this workaround.

**Comment by Eastrall** [comment]
Do you still have this issue with the latest version of Rosalina? Please let me know if this issue is solved. 😄

**Comment by redwyre** [comment]
Ah sorry about not getting back to you, it looks like this is not as useful now but I added the Roslyn packages to UnityNuGet: https://github.com/xoofx/UnityNuGet/blob/master/registry.json#L505
so you can reference the actual packages via open npm
